### Obtener todos los usuarios

GET http://localhost:3000/api/usuarios

### Obtener un usuario 

GET http://localhost:3000/api/usuarios/Facu

### crear un usuario 
POST http://localhost:3000/api/usuarios
Content-Type: application/json

{
    "name" : "Facu",
    "type" : "Vip",
    "mail" : "jiji@gmail.com",
    "peso" : 75,
    "altura" : 174
}

### Modificar elemento completo 
PUT http://localhost:3000/api/usuarios/Facu
Content-Type: application/json

{
    "name" : "Sara",
    "type" : "Vip",
    "mail" : "ash@gmail.com",
    "peso" : 67,
    "altura" : 170

}
### Modificar parte de elemento
PATCH http://localhost:3000/api/usuarios/Sara
Content-Type: application/json

{
  "peso": 65

}
###
DELETE http://localhost:3000/api/usuarios/Sara
Content-Type: application/json