### obtener todos los alimentos

GET http://localhost:3000/api/alimentos

### obtener un alimento

get http://localhost:3000/api/alimentos/1

### crear un nuevo alimento

POST http://localhost:3000/api/alimentos
Content-Type: application/json

{
  "nombre": "Yogurt",
  "marca": "Sancor",
  "Presentacion": null,
  "unidadMedida": "gramos"

}
### Modificar elemento completo 
put http://localhost:3000/api/alimentos/1
Content-Type: application/json

{
  "nombre": "Yot", 
  "marca": "Sancor", 
  "presentacion": null, 
  "unidadMedida": "kilos"

}
### Modificar parte de elemento
PATCH http://localhost:3000/api/alimentos/1
Content-Type: application/json

{
  "marca": "Ilolay"

}
###
DELETE http://localhost:3000/api/alimentos/5
Content-Type: application/json