### Obtener todos los alimentoNutriente
GET http://localhost:3000/api/alimentoNutriente

### Obtener un alimentoNutriente
GET http://localhost:3000/api/alimentoNutriente/1

### Crear un alimentoNutriente
POST http://localhost:3000/api/alimentoNutriente
Content-Type: application/json
{
  "idAlimento": 1,
  "idNutriente": [1,2],
  "cantidad": 10
}

### Modificar alimentoNutriente completo
PUT http://localhost:3000/api/alimentoNutriente/1
Content-Type: application/json
{
  "idAlimento": 2,
  "idNutriente": [2, 1],
  "cantidad": 20
}

### Modificar parte del alimentoNutriente
PATCH http://localhost:3000/api/alimentoNutriente/1
Content-Type: application/json
{
  "cantidad": 15
}

### Borrar alimentoNutriente
DELETE http://localhost:3000/api/alimentoNutriente/1
